services:
  backend:
    build: ./backend
    ports:
      - "80:80"      # Puerto para Nginx (HTTP)
      - "443:443"    # Puerto para Nginx (HTTPS)
      - "3000:3000"  # Puerto para el backend de Node.js
    depends_on:
      - db
    command: ["./wait-for-it.sh", "db:3306", "--", "npm", "start"]
    volumes:
      - ./backend:/app  # Volumen para los archivos del backend
    working_dir: /app
    environment:
      DB_HOST: db
      DB_USER: root
      DB_PASSWORD: password
      DB_NAME: registro_usuarios

  frontend:
    build: ./frontend
    ports:
      - "8080:80"  # Cambié el puerto a 8080 para evitar conflictos con Nginx

  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: registro_usuarios
      MYSQL_USER: root
      MYSQL_PASSWORD: password
    ports:
      - "3307:3306"  # Cambié el puerto a 3307 para evitar conflictos
    volumes:
      - db_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 3

volumes:
  db_data: