services:
  backend:
    build: ./backend
    ports:
      - "3000:3000"
    depends_on:
      - db
    command: ["./wait-for-it.sh", "db:3306", "--", "npm", "start"]  # Asegúrate de que este comando sea correcto
    volumes:
      - ./backend:/app  # Asegúrate de que esta ruta sea correcta
    working_dir: /app  # Establece el directorio de trabajo

  frontend:
    build: ./frontend
    ports:
      - "80:80"

  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: password  # Cambia esto a una contraseña segura
      MYSQL_DATABASE: registro_usuarios
    ports:
      - "3307:3306"

volumes:
  db_data: