version: "3.8"
services:
  backend:
    build: ./backend
    ports:
      - "3000:3000"
    depends_on:
      - db
    command: ["./wait-for-it.sh", "db:3306", "--", "npm", "start"]  
    volumes:
      - ./backend:/app  
    working_dir: /app  # Establece el directorio de trabajo

  frontend:
    build: ./frontend
    ports:
      - "80:80"  

  nginx:
    build: ./nginx  # Esto asume que hay un directorio nginx con un Dockerfile para Nginx
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - backend
      - frontend
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro  
      - ./frontend:/usr/share/nginx/html:ro  
      - ./path/to/certificates:/etc/nginx/certs  

  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: password  
      MYSQL_DATABASE: registro_usuarios
    ports:
      - "3307:3306"

volumes:
  db_data:
