name: Linter Workflow

on:
  push:
    branches:
      - main  # O la rama que estés usando
  pull_request:
    branches:
      - main  # O la rama que estés usando

jobs:
  linter:
    runs-on: ubuntu-latest

    steps:
    # Paso 1: Verifica que el código se haya clonado correctamente
    - name: Checkout repository
      uses: actions/checkout@v3

    # Paso 2: Instala Node.js (ajusta la versión según la que estés usando)
    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'  # Usa la versión de Node.js que estés usando

    # Paso 3: Instala las dependencias del proyecto (incluyendo ESLint)
    - name: Install dependencies
      run: |
        npm install

    # Paso 4: Asegúrate de que ESLint tenga permisos de ejecución
    - name: Give execute permissions to ESLint
      run: chmod +x ./node_modules/.bin/eslint

    # Paso 5: Ejecuta ESLint en todo el proyecto
    - name: Run ESLint
      run: npm run lint # Asegúrate de tener un script "lint" en tu package.json
