name: Run Tests

on:
  push:
    branches:
      - main  # Cambia esto si tu rama principal tiene otro nombre
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: registro_usuarios
          MYSQL_USER: root
          MYSQL_PASSWORD: password
        ports:
          - 3306:3306
        options: >-
          --health-cmd "mysqladmin ping -h localhost"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'  # Cambia esto a la versión de Node.js que estés usando

      - name: Install dependencies
        run: npm install

      - name: Set up environment variables
        run: |
          echo DB_HOST=127.0.0.1 >> .env
          echo DB_USER=root >> .env
          echo DB_PASSWORD=password >> .env
          echo DB_NAME=registro_usuarios >> .env
        env:
          CI: true

      - name: Run tests
        run: npm test
